# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-20 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('system', models.CharField(max_length=64)),
                ('disk', models.CharField(max_length=30)),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='录入时间')),
            ],
        ),
    ]
