# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-15 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='add_time',
            field=models.DateTimeField(auto_now=True, verbose_name='录入时间'),
        ),
    ]
