# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-16 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiskUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_usage', models.IntegerField(null=True, verbose_name='磁盘使用率')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='录入时间')),
            ],
        ),
    ]
