# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-20 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='磁盘使用率')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='录入时间')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DiskUsage', to='home_application.Host')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='内存使用率')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='录入时间')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MemoryUsage', to='home_application.Host')),
            ],
        ),
    ]
