# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-17 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_capacity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_usage', models.IntegerField(null=True, verbose_name='内存使用率')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='录入时间')),
            ],
        ),
    ]
