# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-18 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_capacity', '0003_auto_20190517_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskusage',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='diskusage',
            name='mounted',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='diskusage',
            name='system',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
